todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls'), name='todos'),
    path('user/', include('todo_user.urls'), name='todo_user'),
]

todo_user/urls.py
from django.urls import path
from .views import LoginView, RegisterView, ProfileView, LogoutView, EditProfile

app_name = 'todo_user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit-profile/', EditProfile.as_view(), name='edit_profile'),
]

todos/urls.py
from django.urls import path
from .views import IndexView, TodoListView, TodoDetailView, NewTodoView, DoTheTask, DeleteTask

app_name = 'todos'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('todos/', TodoListView.as_view(), name='todos'),
    path('todos/<str:todo_id>/', TodoDetailView.as_view(), name='todo_detail'),
    path('add_todo/', NewTodoView.as_view(), name='add_todo'),
    path('did_it/', DoTheTask.as_view(), name='did_it'),
    path('delete_todo/', DeleteTask.as_view(), name='delete_todo'),
]

todo_user/models.py
from django.db import models

todos/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    done = models.BooleanField(default=False)
    start_date = models.DateField(default=now)
    end_date = models.DateField(null=True, blank=True)

    class Meta:
        db_table = 'Task'
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

    def __str__(self):
        return self.title

todo_user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout


class LoginView(View):
    template_name = 'login.html'
    http_method_names = ['get', 'post']

    def get(self, request):
        if request.user and request.user.is_authenticated:
            return redirect('todo_user:profile')
        return render(request, self.template_name)

    def post(self, request):
        if request.user and request.user.is_authenticated:
            return redirect('todo_user:profile')
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        if False in [username, password]:
            return render(request, self.template_name, {'error': 'Please enter both username and password'})
        user = authenticate(username=username, password=password)
        try:
            login(request, user)
            return redirect('todos:index')
        except:
            return render(request, self.template_name, {'error': 'Wrong username or password'})


class RegisterView(View):
    template_name = 'register.html'
    http_method_names = ['get', ]

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('todo_user:profile')
        return render(request, self.template_name)


class ProfileView(View):
    template_name = 'profile.html'
    http_method_names = ['get', ]

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        return render(request, self.template_name)


class LogoutView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('todos:index')
        logout(request)
        return redirect('todos:index')


class EditProfile(View):
    http_method_name = ['get', 'post']
    template_name = 'edit_profile.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        return render(request, self.template_name)

    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('todos:index')

        username = request.POST.get('username', False)
        email = request.POST.get('email', False)
        user = request.user

        if False in [username, email]:
            return render(request, self.template_name, {'error': 'Please enter both username and email'})

        user.username = username
        user.email = email
        user.save()
        return redirect('todo_user:profile')

todos/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Task
from django.utils.timezone import now


class IndexView(View):
    http_method_names = ['get', 'post']
    template_name = 'index.html'

    def get(self, request):
        return render(request, self.template_name)


class TodoListView(View):
    http_method_names = ['get', 'post']
    template_name = 'todos_list.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        todos_list = []
        user = request.user
        todos = Task.objects.filter(user=user).order_by('-start_date')
        for todo in todos:
            todos_list.append({
                'id': todo.id,
                'title': todo.title,
                'description': todo.description,
                'done': todo.done,
                'start_date': todo.start_date,
                'end_date': todo.end_date,
            })
        return render(request, self.template_name, {'todo_list': todos_list})


class TodoDetailView(View):
    http_method_names = ['get', 'post']
    template_name = 'single_todo.html'

    def get(self, request, todo_id):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        todo_id = int(self.kwargs.get('todo_id', False))
        if not todo_id:
            return redirect('todo_user:index')
        todo = Task.objects.get(id=todo_id)
        return render(request, self.template_name, {'todo': todo})


class NewTodoView(View):
    http_method_names = ['get', 'post']
    template_name = 'add_task.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        return render(request, self.template_name)

    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        title = request.POST.get('title', False)
        description = request.POST.get('description', False)
        start_date = request.POST.get('start_date', False)

        if not start_date:
            start_date = now()

        if False in [title, description, start_date]:
            return render(request, self.template_name, {'error': 'Please enter all fields'})
        todo = Task.objects.create(title=title, description=description, start_date=start_date, user=request.user)
        return redirect('todos:todos')


class DoTheTask(View):
    http_method_names = ['post',]

    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        todo_id = request.POST.get('task_id', False)
        user = request.user
        if not todo_id:
            return redirect('todos:todos')
        task = Task.objects.get(id=todo_id)
        task.done = 1
        task.save()
        return redirect('todos:todos')


class DeleteTask(View):
    http_method_names = ['post', ]

    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('todo_user:login')
        task_to_delete = int(request.POST.get('task_id', False))
        if not task_to_delete:
            return redirect('todos:index')
        task = Task.objects.get(id=task_to_delete)
        task.delete()
        return redirect('todos:todos')

todo_user/templates/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}'s Profile</title>
    <link rel="stylesheet" href="{% static 'todos.css' %}">
    <style>
        .inlines{
            display: inline-block;
        }
    </style>
</head>
<body>
<div class="head_container">
    <ul class="head_list">
        <li class="head_element"><h1>Edit your profile</h1></li>
        <li class="head_element"><a href="{% url 'todos:index' %}">Home</a></li>
        <li class="head_element"><a href="{% url 'todo_user:profile' %}">{{ user.username }}</a></li>
        <li class="head_element"><a href="{% url 'todos:add_todo' %}">add new todo</a></li>
    </ul>
</div>

<div style="
    max-width: fit-content;
    margin-left: auto;
    margin-right: auto;
    border: 4px solid black;
    padding: 10px;
    border-radius: 10%;
    align-content: center">
    <form action="{% url 'todo_user:edit_profile' %}" method="post">
        {% csrf_token %}
        <ul class="inlines">
            <li>
                <div>
                    <ul>
                        <li class="inlines"><label for="username">username : </label></li>
                        <li class="inlines"><input type="text" id="username" value="{{ user.username }}" name="username" required></li>
                    </ul>
                </div>
            </li>
            <li>
                <div>
                    <ul>
                        <li class="inlines"><label for="email">email : </label></li>
                        <li class="inlines"><input type="email" id="email" value="{{ user.email }}" name="email" required></li>
                    </ul>
                </div>
            </li>
        </ul>
        <div>
            <input type="submit">
        </div>
    </form>
    {{ error }}
</div>
</body>
</html>

todo_user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<div>
    <form action="{% url 'todo_user:login' %}" method="post">
        <ul>
            {% csrf_token %}
            <li><label for="username">username:</label></li>
            <li><input type="text" name="username" id="username"></li>
            <li><label for="password">password</label></li>
            <li><input type="password" name="password" id="password"></li>
            <li><input type="submit" value="login"></li>
        </ul>
    </form>
</div>
<div>
    <h4 style="color: red">{{ error }}</h4>
</div>
<div>
    <h4><a href="{% url 'todo_user:register' %}">new account</a></h4>
    <h4><a href="{% url 'todos:index' %}">Home</a></h4>
</div>
</body>
</html>

todo_user/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}'s Profile</title>
        <link rel="stylesheet" href="{% static 'todos.css' %}">
</head>
<body>

<div class="head_container">
    <ul class="head_list">
        <li class="head_element"><h1>Profile</h1></li>
        <li class="head_element"><a href="{% url 'todos:index' %}">Home</a></li>
        <li class="head_element"><a href="{% url 'todo_user:profile' %}">{{ user.username }}</a></li>
        <li class="head_element"><a href="{% url 'todo_user:edit_profile' %}">edit profile</a></li>
        <li class="head_element"><a href="{% url 'todos:todos' %}">my tasks</a></li>
        <li class="head_element"><a href="{% url 'todos:add_todo' %}">add new todo</a></li>
        <li class="head_element"><h4><a href="{% url 'todo_user:logout' %}"><button>logout</button></a></h4></li>
    </ul>
</div>

</body>
</html>

todo_user/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<div>
    <form action="" method="post">
        {% csrf_token %}
        <ul>
            <li><label for="username">username:</label></li>
            <li><input type="text" name="username" id="username"></li>
            <li><label for="email">email:</label></li>
            <li><input type="email" name="email" id="email"></li>
            <li><label for="password">password</label></li>
            <li><input type="password" name="password" id="password"></li>
            <li><input type="submit" name="" id="" value="register"></li>
        </ul>
    </form>
</div>
<div>
    {{ error }}
</div>
<div>
    <h4><a href="{% url 'todo_user:login' %}">login</a></h4>
    <h4><a href="{% url 'todos:index' %}"></a></h4>
</div>
</body>
</html>

todos/templates/add_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'todos.css' %}">
</head>
<body>

<div class="head_container">
    <ul class="head_list">
        <li class="head_element"><h1>Add new task</h1></li>
        <li class="head_element"><a href="{% url 'todos:index' %}">Home</a></li>
        <li class="head_element"><a href="{% url 'todo_user:profile' %}">{{ user.username }}</a></li>
        <li class="head_element"><a href="{% url 'todos:add_todo' %}">add new todo</a></li>
    </ul>
</div>

<div style="
    max-width: fit-content;
    margin-left: auto;
    margin-right: auto;
    border: 4px solid black;
    padding: 10px;
    border-radius: 10%;
    align-content: center">
    <form action="{% url 'todos:add_todo' %}" method="post">
        <ul>
            {% csrf_token %}
            <li><label for="title">title:</label></li>
            <li><input type="text" name="title" id="title"></li>
            <li><label for="description">add a description:</label></li>
            <li><textarea name="description" id="description" cols="30" rows="10"></textarea></li>
            <li><label for="start_date">enter start day(leave blank for current time)</label></li>
            <li><input type="date" id="start_date"></li>
            <li><input type="submit" value="add new todo"></li>
        </ul>
    </form>
</div>
<div>
    <h4 style="color: red">{{ error }}</h4>
</div>
<div>{{ error }}</div>
</body>
</html>

todos/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'todos.css' %}">
</head>
<body>

<div class="head_container">
    <ul class="head_list">
        <li class="head_element"><h1>ToDoList</h1></li>
        <li class="head_element"><a href="{% url 'todos:index' %}">Home</a></li>
        {% if user and user.is_authenticated %}
            <li class="head_element"><a href="{% url 'todo_user:profile' %}">{{ user.username }}</a></li>
            <li class="head_element"><a href="{% url 'todos:todos' %}">my_todos</a></li>
        {% else %}
            <li class="head_element"><a href="{% url 'todo_user:login' %}">Login</a></li>
        {% endif %}
        <li class="head_element"><a href="{% url 'todos:add_todo' %}">add new todo</a></li>
    </ul>
</div>

</body>
</html>

todos/templates/single_todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<div style="border: 4px solid aqua; border-radius: 20px">
    <ul style="align-content: center">
        <li style="display: inline-block"><a href="{% url 'todos:index' %}">Home</a></li>
        <li style="display: inline-block"><a href="{% url 'todo_user:profile' %}">{{ user.username }}</a></li>
    </ul>
</div>

<ul style="border: 2px solid black; border-radius: 20px ">
    <li><h3>{{ todo.title }}</h3></li>
    <li><h3>start at : {{ todo.start_date }}</h3></li>
    {% if todo.done %}
        <li><h3>you did it!</h3></li>
        <li><h3>finish data : {{ todo.end_date }}</h3></li>
    {% else %}
        <li><h3>not done yet</h3></li>
    {% endif %}
    <li>
        <h3>{{ todo.description }}</h3>
    </li>
</ul>
</body>
</html>

todos/templates/todos_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todos</title>
    <link rel="stylesheet" href="{% static 'todos.css' %}">
</head>
<body>

<div class="head_container">
    <ul class="head_list">
        <li class="head_element"><h1>Your tasks</h1></li>
        <li class="head_element"><a href="{% url 'todos:index' %}">Home</a></li>
        <li class="head_element"><a href="{% url 'todo_user:profile' %}">{{ user.username }}</a></li>
        <li class="head_element"><a href="{% url 'todos:add_todo' %}">add new todo</a></li>
    </ul>
</div>

{% for todo in todo_list %}
    <div style="width: 90%; display: inline-block">
        <div class="todo_container">
            <h3><a class="todo_title" href="{% url 'todos:todo_detail' todo.id %}">{{ todo.title }}</a></h3>
            <h3>start at : {{ todo.start_date }}</h3>
            {% if todo.done %}
                <h3>you did it!</h3>
                <h3>finish data : {{ todo.end_date }}</h3>
            {% else %}
                <h3>not done yet</h3>
            {% endif %}
        </div>
    </div>

    <div style="display: inline-block">
        {% if not todo.done %}
            <form method="post" action="{% url 'todos:did_it' %}">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="{{ todo.id }}">
                <input type="submit" value="I did it">
            </form>
        {% endif %}
        <form action="{% url 'todos:delete_todo' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="task_id" value="{{ todo.id }}">
            <input type="submit" value="delete this task">
        </form>
    </div>
{% endfor %}

</body>
</html>